sudo: required
services:
  - docker

before_install: 
  - docker build -t rahulkumartonk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rahulkumartonk/docker-react npm run test --coverage

